// Single source of truth for the Influencer Manager module.
// Every Top Bar nav item + Wall page is configured here.
// When the backend is wired later, these slugs map 1:1 to API resources.

export type WallKpi = {
  label: string;
  hint?: string;
};

export type WallSection = {
  label: string;
  description?: string;
};

export type WallConfig = {
  slug: string;
  to: string;
  title: string;
  shortTitle?: string;
  description: string;
  group: "overview" | "lifecycle" | "growth" | "money" | "operations" | "system";
  primaryAction?: string;
  secondaryActions?: string[];
  kpis: WallKpi[];
  sections: WallSection[];
  tableTitle?: string;
  tableColumns?: string[];
  emptyTitle?: string;
  emptyDescription?: string;
};

export const WALLS: WallConfig[] = [
  {
    slug: "dashboard",
    to: "/",
    title: "Influencer Operations Dashboard",
    shortTitle: "Dashboard",
    description:
      "Global overview of every Influencer, Creator and Partner across all countries and platforms.",
    group: "overview",
    primaryAction: "New Campaign",
    secondaryActions: ["Invite Creator", "Export Snapshot"],
    kpis: [
      { label: "Total Influencers" },
      { label: "Verified" },
      { label: "Pending Approval" },
      { label: "Suspended" },
      { label: "Countries" },
      { label: "Platforms Connected" },
      { label: "Active Campaigns" },
      { label: "Leads Generated" },
      { label: "Sales Generated" },
      { label: "Revenue" },
      { label: "Commission" },
      { label: "Pending Payouts" },
    ],
    sections: [
      { label: "Live Activity" },
      { label: "Top Creators" },
      { label: "Trending Campaigns" },
      { label: "Global Creator Map" },
      { label: "Conversion Funnel" },
      { label: "Quick Actions" },
    ],
  },
  {
    slug: "applications",
    to: "/applications",
    title: "Creator Applications",
    shortTitle: "Applications",
    description:
      "Review incoming creator applications, identity verification, brand fit and risk assessment.",
    group: "lifecycle",
    primaryAction: "New Application",
    secondaryActions: ["Bulk Approve", "Bulk Reject", "Import CSV"],
    kpis: [
      { label: "Submitted" },
      { label: "In Review" },
      { label: "Awaiting KYC" },
      { label: "Approved Today" },
      { label: "Rejected Today" },
      { label: "Average Review Time" },
    ],
    sections: [
      { label: "Creator Registration" },
      { label: "Identity Verification" },
      { label: "KYC" },
      { label: "Social Verification" },
      { label: "Audience Verification" },
      { label: "Brand Review" },
      { label: "Interview Notes" },
      { label: "Approval Workflow" },
      { label: "Agreement" },
      { label: "Audit Timeline" },
      { label: "Risk Assessment" },
    ],
    tableTitle: "Application Queue",
    tableColumns: ["Applicant", "Country", "Submitted", "Stage", "Risk", "Reviewer", "Status"],
  },
  {
    slug: "influencers",
    to: "/influencers",
    title: "Master Influencer Directory",
    shortTitle: "Influencers",
    description:
      "Search, segment and operate on every Influencer in the network. Built for one million plus records.",
    group: "lifecycle",
    primaryAction: "Add Influencer",
    secondaryActions: ["Bulk Assign", "Bulk Message", "Export"],
    kpis: [
      { label: "Total Influencers" },
      { label: "Verified" },
      { label: "Tier A" },
      { label: "Tier B" },
      { label: "Tier C" },
      { label: "At Risk" },
    ],
    sections: [
      { label: "All Influencers" },
      { label: "Verified" },
      { label: "Pending" },
      { label: "Suspended" },
      { label: "Watchlist" },
      { label: "Segments" },
      { label: "Saved Views" },
    ],
    tableTitle: "Directory",
    tableColumns: [
      "Profile",
      "Country",
      "Languages",
      "Categories",
      "Followers",
      "Engagement",
      "Revenue",
      "Commission",
      "Health",
      "Status",
    ],
  },
  {
    slug: "creator-profiles",
    to: "/creator-profiles",
    title: "Creator Profiles",
    shortTitle: "Creator Profiles",
    description:
      "Deep creator profile records — biography, niche, audience, portfolio, ratings and verification state.",
    group: "lifecycle",
    primaryAction: "Open Profile",
    secondaryActions: ["Verify", "Request Update"],
    kpis: [
      { label: "Profiles" },
      { label: "Verified" },
      { label: "Avg. Rating" },
      { label: "With Portfolio" },
      { label: "Missing Documents" },
      { label: "Languages Covered" },
    ],
    sections: [
      { label: "Biography" },
      { label: "Skills" },
      { label: "Niche" },
      { label: "Audience" },
      { label: "Languages" },
      { label: "Availability" },
      { label: "Portfolio" },
      { label: "Achievements" },
      { label: "Ratings" },
      { label: "Verification" },
      { label: "Documents" },
    ],
    tableTitle: "Creator Profile Index",
    tableColumns: ["Creator", "Niche", "Audience Size", "Rating", "Verification", "Last Updated"],
  },
  {
    slug: "social-accounts",
    to: "/social-accounts",
    title: "Connected Social Accounts",
    shortTitle: "Social Accounts",
    description:
      "Every connected social handle across YouTube, Instagram, TikTok, X, LinkedIn, Telegram and more.",
    group: "lifecycle",
    primaryAction: "Connect Account",
    secondaryActions: ["Re-verify", "Refresh Metrics"],
    kpis: [
      { label: "Connected Accounts" },
      { label: "Verified Handles" },
      { label: "Platforms" },
      { label: "Followers (sum)" },
      { label: "Avg. Engagement" },
      { label: "Sync Issues" },
    ],
    sections: [
      { label: "YouTube" },
      { label: "Instagram" },
      { label: "Facebook" },
      { label: "LinkedIn" },
      { label: "TikTok" },
      { label: "X" },
      { label: "Telegram" },
      { label: "WhatsApp Channel" },
      { label: "Pinterest" },
      { label: "Threads" },
      { label: "Website" },
    ],
    tableTitle: "Account Index",
    tableColumns: ["Creator", "Platform", "Handle", "Followers", "Engagement", "Verified", "Status"],
  },
  {
    slug: "campaigns",
    to: "/campaigns",
    title: "Campaign Management",
    shortTitle: "Campaigns",
    description:
      "Plan, launch and govern brand campaigns. Manage briefs, budgets, deliverables and approvals.",
    group: "growth",
    primaryAction: "Create Campaign",
    secondaryActions: ["Duplicate", "Assign Creators", "Export Brief"],
    kpis: [
      { label: "Active" },
      { label: "Scheduled" },
      { label: "In Review" },
      { label: "Completed" },
      { label: "Budget Allocated" },
      { label: "Budget Spent" },
    ],
    sections: [
      { label: "All Campaigns" },
      { label: "Drafts" },
      { label: "Active" },
      { label: "Scheduled" },
      { label: "Completed" },
      { label: "Archived" },
      { label: "Templates" },
    ],
    tableTitle: "Campaigns",
    tableColumns: ["Campaign", "Brand", "Creators", "Budget", "Start", "End", "Status"],
  },
  {
    slug: "leads",
    to: "/leads",
    title: "Lead Management",
    shortTitle: "Leads",
    description:
      "Track every lead generated by creators — from first touch to qualified opportunity and conversion.",
    group: "growth",
    primaryAction: "New Lead",
    secondaryActions: ["Assign", "Import", "Export"],
    kpis: [
      { label: "New Leads" },
      { label: "Qualified" },
      { label: "Contacted" },
      { label: "Meetings Booked" },
      { label: "Won" },
      { label: "Lost" },
    ],
    sections: [
      { label: "All Leads" },
      { label: "New" },
      { label: "Qualified" },
      { label: "Pipeline" },
      { label: "Follow-up" },
      { label: "Meetings" },
      { label: "Won" },
      { label: "Lost" },
    ],
    tableTitle: "Leads",
    tableColumns: ["Lead", "Source Creator", "Country", "Stage", "Owner", "Created", "Status"],
  },
  {
    slug: "customers",
    to: "/customers",
    title: "Customers Attributed to Creators",
    shortTitle: "Customers",
    description:
      "Customers acquired through creator referrals — orders, subscriptions, licenses and lifetime value.",
    group: "growth",
    primaryAction: "Open Customer",
    secondaryActions: ["Export"],
    kpis: [
      { label: "Customers" },
      { label: "Paying Customers" },
      { label: "Active Subscriptions" },
      { label: "Lifetime Revenue" },
      { label: "Avg. Order Value" },
      { label: "Churn (30d)" },
    ],
    sections: [
      { label: "All Customers" },
      { label: "Active" },
      { label: "Subscriptions" },
      { label: "Licenses" },
      { label: "Support" },
      { label: "Purchase History" },
    ],
    tableTitle: "Customers",
    tableColumns: ["Customer", "Attributed Creator", "Country", "Orders", "Revenue", "Status"],
  },
  {
    slug: "marketplace-promotions",
    to: "/marketplace-promotions",
    title: "Marketplace Promotions",
    shortTitle: "Marketplace",
    description:
      "Featured products, homepage placement, banners and SEO surfaces awarded to creators.",
    group: "growth",
    primaryAction: "Promote Item",
    secondaryActions: ["Schedule", "Pause All"],
    kpis: [
      { label: "Active Promotions" },
      { label: "Featured Products" },
      { label: "Banner Slots" },
      { label: "Impressions" },
      { label: "Click-through Rate" },
      { label: "Attributed Sales" },
    ],
    sections: [
      { label: "Featured Products" },
      { label: "Homepage Promotion" },
      { label: "Banner Placement" },
      { label: "Campaign Promotion" },
      { label: "Categories" },
      { label: "SEO Promotion" },
      { label: "Visibility" },
    ],
    tableTitle: "Promotions",
    tableColumns: ["Promotion", "Surface", "Creator", "Start", "End", "Impressions", "Status"],
  },
  {
    slug: "referral-links",
    to: "/referral-links",
    title: "Referral Links",
    shortTitle: "Referral Links",
    description:
      "Personal referral URLs issued to creators with click, conversion and revenue attribution.",
    group: "money",
    primaryAction: "Generate Link",
    secondaryActions: ["Bulk Generate", "Export"],
    kpis: [
      { label: "Active Links" },
      { label: "Clicks" },
      { label: "Conversions" },
      { label: "Conversion Rate" },
      { label: "Attributed Revenue" },
      { label: "Earned Commission" },
    ],
    sections: [
      { label: "All Links" },
      { label: "By Creator" },
      { label: "By Campaign" },
      { label: "By Product" },
      { label: "Expired" },
    ],
    tableTitle: "Referral Links",
    tableColumns: ["Slug", "Creator", "Destination", "Clicks", "Conversions", "Revenue", "Status"],
  },
  {
    slug: "affiliate-links",
    to: "/affiliate-links",
    title: "Affiliate Links",
    shortTitle: "Affiliate Links",
    description:
      "Affiliate URLs with commission rules, cookie windows and partner-grade tracking.",
    group: "money",
    primaryAction: "Generate Affiliate Link",
    secondaryActions: ["Bulk Generate", "Export"],
    kpis: [
      { label: "Active Affiliates" },
      { label: "Active Links" },
      { label: "Clicks" },
      { label: "Conversions" },
      { label: "Attributed Revenue" },
      { label: "Commission Owed" },
    ],
    sections: [
      { label: "All Links" },
      { label: "By Partner" },
      { label: "By Product" },
      { label: "By Campaign" },
      { label: "Rules" },
    ],
    tableTitle: "Affiliate Links",
    tableColumns: ["Slug", "Partner", "Product", "Commission", "Clicks", "Revenue", "Status"],
  },
  {
    slug: "coupons",
    to: "/coupons",
    title: "Coupons",
    shortTitle: "Coupons",
    description:
      "Discount codes assigned to creators with usage limits, expiry and campaign mapping.",
    group: "money",
    primaryAction: "Create Coupon",
    secondaryActions: ["Bulk Create", "Export"],
    kpis: [
      { label: "Active Coupons" },
      { label: "Redemptions" },
      { label: "Avg. Discount" },
      { label: "Revenue Driven" },
      { label: "Expiring Soon" },
      { label: "Disabled" },
    ],
    sections: [
      { label: "All Coupons" },
      { label: "Active" },
      { label: "Scheduled" },
      { label: "Expired" },
      { label: "Disabled" },
      { label: "Rules" },
    ],
    tableTitle: "Coupons",
    tableColumns: ["Code", "Creator", "Discount", "Used / Limit", "Expires", "Campaign", "Status"],
  },
  {
    slug: "commissions",
    to: "/commissions",
    title: "Commissions",
    shortTitle: "Commissions",
    description:
      "Commission rules, calculations, adjustments and full history across every creator.",
    group: "money",
    primaryAction: "New Rule",
    secondaryActions: ["Recalculate", "Export"],
    kpis: [
      { label: "Pending" },
      { label: "Approved" },
      { label: "Paid (MTD)" },
      { label: "Adjustments" },
      { label: "Disputed" },
      { label: "Avg. Rate" },
    ],
    sections: [
      { label: "Commission Rules" },
      { label: "Pending" },
      { label: "Approved" },
      { label: "Paid" },
      { label: "Adjustments" },
      { label: "Disputed" },
      { label: "History" },
    ],
    tableTitle: "Commission Ledger",
    tableColumns: ["Date", "Creator", "Source", "Gross", "Rate", "Commission", "Status"],
  },
  {
    slug: "wallet",
    to: "/wallet",
    title: "Wallets",
    shortTitle: "Wallet",
    description:
      "Per-creator wallet balances, transaction history and reconciled ledger view.",
    group: "money",
    primaryAction: "Adjustment",
    secondaryActions: ["Export Ledger"],
    kpis: [
      { label: "Total Balance" },
      { label: "Available" },
      { label: "On Hold" },
      { label: "Reserved" },
      { label: "Currencies" },
      { label: "Reconciled" },
    ],
    sections: [
      { label: "Wallets" },
      { label: "Transactions" },
      { label: "Holds" },
      { label: "Adjustments" },
      { label: "Reconciliation" },
    ],
    tableTitle: "Wallets",
    tableColumns: ["Creator", "Currency", "Available", "On Hold", "Last Activity", "Status"],
  },
  {
    slug: "payouts",
    to: "/payouts",
    title: "Payouts",
    shortTitle: "Payouts",
    description:
      "Withdraw requests, payout batches, settlement status and full audit trail.",
    group: "money",
    primaryAction: "Run Payout Batch",
    secondaryActions: ["Approve Selected", "Reject Selected", "Export"],
    kpis: [
      { label: "Pending Requests" },
      { label: "Awaiting Approval" },
      { label: "Scheduled" },
      { label: "Paid (MTD)" },
      { label: "Failed" },
      { label: "Total Amount" },
    ],
    sections: [
      { label: "Withdraw Requests" },
      { label: "Batches" },
      { label: "Scheduled" },
      { label: "Completed" },
      { label: "Failed" },
      { label: "Bank / UPI / PayPal / Wise" },
      { label: "Audit" },
    ],
    tableTitle: "Payouts",
    tableColumns: ["Request", "Creator", "Method", "Amount", "Requested", "Settled", "Status"],
  },
  {
    slug: "performance",
    to: "/performance",
    title: "Creator Performance",
    shortTitle: "Performance",
    description:
      "Growth, engagement, reach, clicks, ROI and a unified performance score per creator.",
    group: "growth",
    primaryAction: "Compare",
    secondaryActions: ["Export"],
    kpis: [
      { label: "Followers Growth" },
      { label: "Engagement" },
      { label: "Reach" },
      { label: "Impressions" },
      { label: "Clicks" },
      { label: "CTR" },
      { label: "Revenue" },
      { label: "ROI" },
    ],
    sections: [
      { label: "Leaderboard" },
      { label: "Followers Growth" },
      { label: "Engagement" },
      { label: "Reach & Impressions" },
      { label: "Conversion" },
      { label: "Performance Score" },
    ],
    tableTitle: "Performance",
    tableColumns: ["Creator", "Followers", "Engagement", "Clicks", "Revenue", "ROI", "Score"],
  },
  {
    slug: "content-library",
    to: "/content-library",
    title: "Content Library",
    shortTitle: "Content Library",
    description:
      "Posts, videos, reels, stories, images, PDFs and reusable templates submitted by creators.",
    group: "operations",
    primaryAction: "Upload Content",
    secondaryActions: ["Approve Selected", "Export"],
    kpis: [
      { label: "Items" },
      { label: "Approved" },
      { label: "Pending Review" },
      { label: "Rejected" },
      { label: "Downloads" },
      { label: "Storage Used" },
    ],
    sections: [
      { label: "All Content" },
      { label: "Posts" },
      { label: "Videos" },
      { label: "Reels" },
      { label: "Stories" },
      { label: "Images" },
      { label: "PDF" },
      { label: "Templates" },
      { label: "Campaign Assets" },
    ],
    tableTitle: "Content",
    tableColumns: ["Title", "Type", "Creator", "Campaign", "Submitted", "Approval", "Status"],
  },
  {
    slug: "media-assets",
    to: "/media-assets",
    title: "Media Assets",
    shortTitle: "Media Assets",
    description:
      "Centrally managed brand assets distributed to creators — logos, banners, videos, marketing kits.",
    group: "operations",
    primaryAction: "Upload Asset",
    secondaryActions: ["New Version", "Distribute"],
    kpis: [
      { label: "Assets" },
      { label: "Brand Kits" },
      { label: "Downloads" },
      { label: "New This Week" },
      { label: "Versions" },
      { label: "Storage Used" },
    ],
    sections: [
      { label: "Brand Assets" },
      { label: "Logos" },
      { label: "Banners" },
      { label: "Videos" },
      { label: "Product Images" },
      { label: "Marketing Kits" },
      { label: "Version History" },
    ],
    tableTitle: "Assets",
    tableColumns: ["Asset", "Type", "Version", "Owner", "Updated", "Downloads", "Status"],
  },
  {
    slug: "reviews",
    to: "/reviews",
    title: "Reviews & Ratings",
    shortTitle: "Reviews",
    description:
      "Brand and customer reviews about creators, with moderation, reports and analytics.",
    group: "operations",
    primaryAction: "Moderate Queue",
    secondaryActions: ["Export"],
    kpis: [
      { label: "Reviews" },
      { label: "Average Rating" },
      { label: "Pending Moderation" },
      { label: "Reported" },
      { label: "Hidden" },
      { label: "Response Rate" },
    ],
    sections: [
      { label: "All Reviews" },
      { label: "Brand Reviews" },
      { label: "Customer Reviews" },
      { label: "Pending Moderation" },
      { label: "Reported" },
    ],
    tableTitle: "Reviews",
    tableColumns: ["Reviewer", "Creator", "Rating", "Source", "Submitted", "Status"],
  },
  {
    slug: "support",
    to: "/support",
    title: "Creator Support",
    shortTitle: "Support",
    description:
      "Tickets, live chat, WhatsApp, email and call queues with SLA tracking and escalations.",
    group: "operations",
    primaryAction: "New Ticket",
    secondaryActions: ["Assign", "Escalate"],
    kpis: [
      { label: "Open Tickets" },
      { label: "Awaiting Response" },
      { label: "Resolved Today" },
      { label: "Avg. First Reply" },
      { label: "SLA Breaches" },
      { label: "CSAT" },
    ],
    sections: [
      { label: "All Tickets" },
      { label: "Live Chat" },
      { label: "WhatsApp" },
      { label: "Email" },
      { label: "Calls" },
      { label: "Knowledge Base" },
      { label: "SLA" },
      { label: "Escalation" },
    ],
    tableTitle: "Tickets",
    tableColumns: ["Ticket", "Creator", "Channel", "Priority", "Owner", "SLA", "Status"],
  },
  {
    slug: "communication",
    to: "/communication",
    title: "Communication Center",
    shortTitle: "Communication",
    description:
      "Broadcasts, announcements, emails, SMS, WhatsApp, push notifications and meeting logs.",
    group: "operations",
    primaryAction: "New Broadcast",
    secondaryActions: ["Schedule", "Templates"],
    kpis: [
      { label: "Sent (7d)" },
      { label: "Delivered" },
      { label: "Open Rate" },
      { label: "Click Rate" },
      { label: "Bounces" },
      { label: "Unsubscribes" },
    ],
    sections: [
      { label: "Broadcast" },
      { label: "Announcements" },
      { label: "Email" },
      { label: "SMS" },
      { label: "WhatsApp" },
      { label: "Push Notifications" },
      { label: "Meetings" },
      { label: "Internal Chat" },
      { label: "Logs" },
    ],
    tableTitle: "Communication Logs",
    tableColumns: ["Date", "Channel", "Audience", "Sent", "Delivered", "Opened", "Status"],
  },
  {
    slug: "documents",
    to: "/documents",
    title: "Documents",
    shortTitle: "Documents",
    description:
      "Influencer agreements, NDAs, KYC, invoices, tax documents and digital signatures.",
    group: "operations",
    primaryAction: "Upload Document",
    secondaryActions: ["Send for Signature", "New Template"],
    kpis: [
      { label: "Documents" },
      { label: "Signed" },
      { label: "Awaiting Signature" },
      { label: "Expiring Soon" },
      { label: "Templates" },
      { label: "Storage Used" },
    ],
    sections: [
      { label: "Influencer Agreement" },
      { label: "NDA" },
      { label: "KYC" },
      { label: "Invoices" },
      { label: "Tax Documents" },
      { label: "Certificates" },
      { label: "Digital Signature" },
      { label: "Version History" },
    ],
    tableTitle: "Documents",
    tableColumns: ["Document", "Creator", "Type", "Version", "Updated", "Signed", "Status"],
  },
  {
    slug: "compliance",
    to: "/compliance",
    title: "Compliance & Risk",
    shortTitle: "Compliance",
    description:
      "Identity, tax, content, brand policy, copyright and trademark compliance with risk alerts.",
    group: "operations",
    primaryAction: "Open Case",
    secondaryActions: ["Run Check", "Export Audit"],
    kpis: [
      { label: "Open Cases" },
      { label: "High Risk" },
      { label: "Medium Risk" },
      { label: "Resolved (30d)" },
      { label: "Policy Violations" },
      { label: "Audit Events (24h)" },
    ],
    sections: [
      { label: "Identity Verification" },
      { label: "Tax Compliance" },
      { label: "Content Compliance" },
      { label: "Brand Policy" },
      { label: "Copyright" },
      { label: "Trademark" },
      { label: "Legal Status" },
      { label: "Risk Alerts" },
      { label: "Audit Logs" },
    ],
    tableTitle: "Compliance Cases",
    tableColumns: ["Case", "Creator", "Type", "Risk", "Owner", "Opened", "Status"],
  },
  {
    slug: "analytics",
    to: "/analytics",
    title: "Analytics",
    shortTitle: "Analytics",
    description:
      "Revenue, campaigns, leads, sales, traffic, platforms, countries, growth and AI insights.",
    group: "system",
    primaryAction: "New Dashboard",
    secondaryActions: ["Share", "Export"],
    kpis: [
      { label: "Revenue (MTD)" },
      { label: "Campaigns" },
      { label: "Leads" },
      { label: "Conversion" },
      { label: "Top Country" },
      { label: "Top Platform" },
    ],
    sections: [
      { label: "Revenue" },
      { label: "Campaigns" },
      { label: "Leads" },
      { label: "Sales" },
      { label: "Traffic" },
      { label: "Platforms" },
      { label: "Countries" },
      { label: "Growth" },
      { label: "Forecast" },
      { label: "AI Insights" },
    ],
  },
  {
    slug: "reports",
    to: "/reports",
    title: "Reports",
    shortTitle: "Reports",
    description:
      "Generate, schedule and distribute campaign, revenue, commission and payout reports.",
    group: "system",
    primaryAction: "New Report",
    secondaryActions: ["Schedule", "Export PDF", "Export Excel", "Export CSV"],
    kpis: [
      { label: "Saved Reports" },
      { label: "Scheduled" },
      { label: "Generated (30d)" },
      { label: "Recipients" },
      { label: "Failed Runs" },
      { label: "Storage Used" },
    ],
    sections: [
      { label: "All Reports" },
      { label: "Campaign" },
      { label: "Revenue" },
      { label: "Commission" },
      { label: "Lead" },
      { label: "Sales" },
      { label: "Influencer" },
      { label: "Payout" },
      { label: "Scheduled" },
    ],
    tableTitle: "Reports",
    tableColumns: ["Report", "Type", "Owner", "Schedule", "Last Run", "Recipients", "Status"],
  },
  {
    slug: "brands",
    to: "/brands",
    title: "Brand Partners",
    shortTitle: "Brands",
    description:
      "Every brand connected to the Boss Panel — contracts, campaigns, spend and creator rosters.",
    group: "lifecycle",
    primaryAction: "Add Brand",
    secondaryActions: ["Import Brands", "Export"],
    kpis: [
      { label: "Total Brands" },
      { label: "Active" },
      { label: "In Onboarding" },
      { label: "Contracts Expiring" },
      { label: "Live Campaigns" },
      { label: "Committed Spend" },
    ],
    sections: [
      { label: "Directory" },
      { label: "Onboarding" },
      { label: "Contracts" },
      { label: "Campaigns" },
      { label: "Spend" },
      { label: "Roster" },
      { label: "Contacts" },
      { label: "Documents" },
    ],
    tableTitle: "Brand Directory",
    tableColumns: ["Brand", "Industry", "Country", "Contracts", "Live Campaigns", "Spend", "Status"],
  },
  {
    slug: "collaborations",
    to: "/collaborations",
    title: "Collaborations",
    shortTitle: "Collaborations",
    description:
      "Every brand collaboration, partnership request and deliverable across the creator network.",
    group: "lifecycle",
    primaryAction: "New Collaboration",
    secondaryActions: ["Import", "Export"],
    kpis: [
      { label: "Requests" },
      { label: "In Negotiation" },
      { label: "Active Deals" },
      { label: "Completed" },
      { label: "Rejected" },
      { label: "Total Value" },
    ],
    sections: [
      { label: "Requests" },
      { label: "Negotiation" },
      { label: "Active Deals" },
      { label: "Deliverables" },
      { label: "Completed" },
      { label: "Rejected" },
      { label: "Contracts" },
      { label: "Timeline" },
    ],
    tableTitle: "Collaboration Pipeline",
    tableColumns: ["Deal", "Brand", "Creator", "Stage", "Deliverables", "Value", "Close Date", "Status"],
  },
  {
    slug: "rewards",
    to: "/rewards",
    title: "Rewards & Incentives",
    shortTitle: "Rewards",
    description:
      "Bonuses, tier rewards, referral incentives and seasonal boosts awarded to creators.",
    group: "money",
    primaryAction: "New Reward",
    secondaryActions: ["Bulk Award", "Export"],
    kpis: [
      { label: "Active Rewards" },
      { label: "Awarded This Month" },
      { label: "Recipients" },
      { label: "Value Awarded" },
      { label: "Pending Claims" },
      { label: "Redeemed" },
    ],
    sections: [
      { label: "Programs" },
      { label: "Tier Bonuses" },
      { label: "Referral Incentives" },
      { label: "Seasonal Boosts" },
      { label: "Claims" },
      { label: "Redemptions" },
      { label: "Ledger" },
    ],
    tableTitle: "Rewards Ledger",
    tableColumns: ["Reward", "Type", "Recipient", "Value", "Awarded", "Expires", "Status"],
  },
  {
    slug: "achievements",
    to: "/achievements",
    title: "Achievements & Ranks",
    shortTitle: "Achievements",
    description:
      "Badges, milestones, leaderboards and rank progression for the creator network.",
    group: "growth",
    primaryAction: "New Badge",
    secondaryActions: ["Recompute Ranks", "Export"],
    kpis: [
      { label: "Badges" },
      { label: "Milestones" },
      { label: "Ranked Creators" },
      { label: "Top Rank Holders" },
      { label: "Awarded This Month" },
      { label: "Pending Reviews" },
    ],
    sections: [
      { label: "Badges" },
      { label: "Milestones" },
      { label: "Leaderboard" },
      { label: "Rank Tiers" },
      { label: "Awarded" },
      { label: "Rules" },
    ],
    tableTitle: "Achievements Catalog",
    tableColumns: ["Badge", "Category", "Criteria", "Holders", "Last Awarded", "Status"],
  },
  {
    slug: "verification",
    to: "/verification",
    title: "Verification Center",
    shortTitle: "Verification",
    description:
      "Identity, social, company, bank, tax and KYC verification for every creator on the platform.",
    group: "operations",
    primaryAction: "New Verification",
    secondaryActions: ["Bulk Verify", "Export"],
    kpis: [
      { label: "Pending" },
      { label: "In Review" },
      { label: "Verified" },
      { label: "Rejected" },
      { label: "Expiring Soon" },
      { label: "Avg. Review Time" },
    ],
    sections: [
      { label: "Identity" },
      { label: "Social" },
      { label: "Company" },
      { label: "Bank" },
      { label: "Tax" },
      { label: "KYC Progress" },
      { label: "Agreements" },
      { label: "Document Viewer" },
    ],
    tableTitle: "Verification Queue",
    tableColumns: ["Creator", "Type", "Submitted", "Reviewer", "Progress", "Expires", "Status"],
  },
  {
    slug: "notifications",
    to: "/notifications",
    title: "Notification Center",
    shortTitle: "Notifications",
    description:
      "Every system alert, approval request, payout event and creator notification in one inbox.",
    group: "system",
    primaryAction: "Compose",
    secondaryActions: ["Mark All Read", "Preferences"],
    kpis: [
      { label: "Unread" },
      { label: "Today" },
      { label: "This Week" },
      { label: "Approvals Waiting" },
      { label: "Alerts" },
      { label: "Templates" },
    ],
    sections: [
      { label: "Inbox" },
      { label: "Approvals" },
      { label: "Alerts" },
      { label: "Announcements" },
      { label: "Sent" },
      { label: "Scheduled" },
      { label: "Templates" },
      { label: "Preferences" },
    ],
    tableTitle: "Notification Inbox",
    tableColumns: ["Subject", "Type", "Audience", "Channel", "Sent", "Delivered", "Status"],
  },
  {
    slug: "settings",
    to: "/settings",
    title: "Module Settings",
    shortTitle: "Settings",
    description:
      "Rules, templates, automation, brand, integrations, security, backup, audit and system health.",
    group: "system",
    primaryAction: "Save Changes",
    secondaryActions: ["Discard", "Restore Defaults"],
    kpis: [
      { label: "Rules" },
      { label: "Templates" },
      { label: "Automations" },
      { label: "Integrations" },
      { label: "API Keys" },
      { label: "Audit Events (24h)" },
    ],
    sections: [
      { label: "Campaign Rules" },
      { label: "Commission Rules" },
      { label: "Referral Rules" },
      { label: "Coupon Rules" },
      { label: "Approval Workflow" },
      { label: "Notification Templates" },
      { label: "Email Templates" },
      { label: "WhatsApp Templates" },
      { label: "Automation Rules" },
      { label: "Brand Settings" },
      { label: "API Keys" },
      { label: "Integrations" },
      { label: "Security" },
      { label: "Backup" },
      { label: "Audit" },
      { label: "System Health" },
    ],
  },
];

export const WALL_BY_SLUG: Record<string, WallConfig> = WALLS.reduce(
  (acc, w) => {
    acc[w.slug] = w;
    return acc;
  },
  {} as Record<string, WallConfig>,
);
